image: java:8

variables:
  GRAILS_VERSION: "3.1.7"
  GRADLE_VERSION: "2.9"

before_script:
  # Update linux
  - apt-get update -qq && apt-get install -y -qq unzip
  # Install SDKMAN
  - curl -sSL https://get.sdkman.io | bash
  # Install Gradle
  - sdk install gradle $GRADLE_VERSION
  - sdk use gradle $GRADLE_VERSION
  # Install Grails
  - sdk install grails $GRAILS_VERSION
  - sdk use grails $GRAILS_VERSION
  # Install Java
  - sdk install java
  # Assign permissions gradlew bash
  - chmod +x gradlew
  - ./gradlew --refresh-dependencies
  - ./gradlew clean

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - grails test war
    - echo $CI_PROJECT_DIR
    - ssh imasd@192.168.100.240 'rm /home/apps/apache-tomcat-8.5.6/apps/ROOT.war'