image: java:8

variables:
  GRAILS_VERSION: "3.1.7"
  GRADLE_VERSION: "2.9"

stages:
  - build
  - test
  - deploy

build:
  before_script:
  # Update linux
  - apt-get update -qq && apt-get install -y -qq unzip
  # Install SDKMAN
  - curl -sSL https://get.sdkman.io | bash
  # Install Gradle
  - sdk install gradle $GRADLE_VERSION
  - sdk use gradle $GRADLE_VERSION
  # Install Grails
  - sdk install grails $GRAILS_VERSION
  - sdk use grails $GRAILS_VERSION
  # Install Java
  - sdk install java
  # Assign permissions execution gradlew bash
  - chmod +x gradlew
  - ./gradlew --refresh-dependencies
  - ./gradlew clean
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - grails test-app
    - ./gradlew sonarqube -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME

deploy:
  stage: deploy
  script:
    - grails test war
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_NAME
    - ssh imasd@192.168.100.240 'rm /home/apps/apache-tomcat-8.5.6/apps/ROOT.war'
    - sleep 10
    - scp $CI_PROJECT_DIR/build/libs/$CI_PROJECT_NAME.war imasd@192.168.100.240:/home/apps/apache-tomcat-8.5.6/apps/ROOT.war